title: SRN-WKYN2G9P3
logo: /assets/profile.png
description: Data Science Portfolio | Apprenticeship Projects | Machine Learning | Analytics
theme: jekyll-theme-minimal

show_downloads: false

github:
  is_project_page: true
